# Generated by Django 4.1.13 on 2025-03-23 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open', models.BooleanField(default=True, verbose_name='Tienda abierta')),
                ('closed_reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='Motivo de cierre')),
                ('manual_override', models.BooleanField(default=False, verbose_name='Cierre manual')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Estado de la tienda',
                'verbose_name_plural': 'Estado de la tienda',
            },
        ),
    ]
