# Generated by Django 4.1.13 on 2025-03-13 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='reference',
            field=models.TextField(blank=True, null=True),
        ),
    ]
